name: ⬣ Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: ⬣ Lint
    uses: mcanshbot/shared-workflows/.github/workflows/lint.yml@main
    with: 
      package-manager: pnpm
      package-manager-version: 7
      node-version: 18